In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('laliga.csv',index_col=False, skiprows=1)

def Goal_diff_count():
    print("Goal Difference")    
    df2=df
    df2['GD']=df2.apply(lambda x:x['GoalsFor']-x['GoalsAgainst'],axis=1)
    print(df2)
    df2=df2.nlargest(len(df2), 'GD')
    #print(df2)
    print("Maximum Goal Difference: ", df2.iloc[0,1])
    print("Minimum Goal Difference: ", df2.iloc[len(df2)-1,1])
    

#print(df)
#print(len(df))

df=df.replace('-',0)
print ("After replacing '-' with 0")
print(df.columns)
df['Debut'] = df['Debut'].apply(lambda x: x[0:4])

df['Debut'] = df['Debut'].astype('int64')

df['GoalsFor'] = df['GoalsFor'].astype('int64')

df['GoalsAgainst'] = df['GoalsAgainst'].astype('int64')

df['GamesWon'] = df['GamesWon'].astype('int64')

df['GamesPlayed'] = df['GamesPlayed'].astype('int64')

df['Debut'] = df['Debut'].astype(np.int64)

print(df.iloc[0,16])
print('Teams Debut between 1930 and 1980')

for i in range(0,len(df)):
    if df.iloc[i,17]>=1930 and df.iloc[i,17]<=1980:
        print(df.iloc[i,1]) 


df['Points'] = df['Points'].astype('int64')


df1=df.nlargest(5, 'Points')
count=0
print("Top 5 Teams on point basis")
for v in df['Team']:
    count=count+1
    print(v)
    if count==int(5):
        break;

Goal_diff_count()


df['Winning Percent']=df.apply(lambda x:(x['GamesWon']/x['GamesPlayed'])*100 if x['GamesPlayed']!=0 else 0,axis=1)

df3=df.nlargest(len(df), 'Winning Percent')

print("Top 5 Teams on goal difference basis")

print(df3['Team'].head(5))

#print("Best")
r = df.groupby('BestPosition')['Points'].sum()
print("Sum of points based on 'Best Position")
print (r)


#df3=df.groupby('BestPosition')

#for pos,

df.to_csv('output.csv',index=False)

After replacing '-' with 0
Index(['Pos', 'Team', 'Seasons', 'Points', 'GamesPlayed', 'GamesWon',
       'GamesDrawn', 'GamesLost', 'GoalsFor', 'GoalsAgainst', 'Champion',
       'Runner-up', 'Third', 'Fourth', 'Fifth', 'Sixth', 'T', 'Debut',
       'Since/LastApp', 'BestPosition'],
      dtype='object')
79
Teams Debut between 1930 and 1980
Valencia
Sevilla
Zaragoza
Real Betis
Deportivo La Coruna
Celta Vigo
Valladolid
Sporting Gijon
Osasuna
Malaga
Oviedo
Mallorca
Las Palmas
Granada
Rayo Vallecano
Elche
Hercules
Tenerife
Murcia
Alaves
Levante
Salamanca
Sabadell
Cadiz
Castellon
Cordoba
Recreativo
Burgos CF
Pontevedra
Gimnastic
Alcoyano
Jaen
AD Almeria
Lleida
Condal
Atletico Tetuan
Cultural Leonesa
Top 5 Teams on point basis
Real Madrid
Barcelona
Atletico Madrid
Valencia
Athletic Bilbao
Goal Difference
    Pos                 Team  Seasons  Points  GamesPlayed  GamesWon  \
0     1          Real Madrid       86    4385         2762      1647
1     2            Barcelona       86    4262         2762      1581
2     3      Atletico Madrid       80    3442         2614      1241
3     4             Valencia       82    3386         2664      1187
4     5      Athletic Bilbao       86    3368         2762      1209
5     6              Sevilla       73    2819         2408       990
6     7             Espanyol       82    2792         2626       948
7     8        Real Sociedad       70    2573         2302       864
8     9             Zaragoza       58    2109         1986       698
9    10           Real Betis       51    1884         1728       606
10   11  Deportivo La Coruna       45    1814         1530       563
11   12           Celta Vigo       51    1789         1698       586
12   13           Valladolid       42    1471         1466       463
13   14     Racing Santander       44    1416         1428       453
14   15       Sporting Gijon       43    1389         1458       471
15   16              Osasuna       37    1351         1318       426
16   17               Malaga       36    1314         1255       390
17   18               Oviedo       38    1174         1192       408
18   19             Mallorca       27    1148          988       333
19   20           Las Palmas       33    1020         1096       367
20   21           Villarreal       17     970          646       266
21   22              Granada       23     667          742       218
22   23       Rayo Vallecano       17     662          652       189
23   24                Elche       21     606          678       203
24   25               Getafe       12     553          456       147
25   26             Hercules       20     538          628       184
26   27             Tenerife       13     510          494       155
27   28               Murcia       18     445          586       145
28   29               Alaves       12     421          380       125
29   30              Levante       11     416          402       113
..  ...                  ...      ...     ...          ...       ...
31   32             Sabadell       14     353          426       129
32   33                Cadiz       12     343          448       104
33   34             Logrones        9     293          346        96
34   35            Castellon       11     285          334       103
35   36             Albacete        7     277          270        76
36   37              Almeria        6     242          228        62
37   38              Cordoba        9     230          282        82
38   39           Compostela        4     190          160        52
39   40           Recreativo        5     188          186        50
40   41            Burgos CF        6     168          204        59
41   42           Pontevedra        6     150          180        53
42   43             Numancia        4     148          152        37
43   44                Eibar        3     132          114        35
44   45               Arenas        7     107          130        43
45   46          Real Burgos        3      96          114        26
46   47            Gimnastic        4      91          116        34
47   48          Extremadura        2      83           80        20
48   49               Merida        2      81           80        19
49   50             Alcoyano        4      76          108        30
50   51                 Jaen        3      71           90        29
51   52           Real Union        4      56           72        21
52   53           AD Almeria        2      52           68        17
53   54               Europa        3      42           54        18
54   55               Lleida        2      40           68        13
55   56              Leganes        1      35           38         8
56   57                Xerez        1      34           38         8
57   58               Condal        1      22           30         7
58   59      Atletico Tetuan        1      19           30         7
59   60     Cultural Leonesa        1      14           30         5
60   61               Girona        1       0            0         0

   GamesDrawn GamesLost  GoalsFor  GoalsAgainst  ...  Runner-up Third Fourth  \
0         552       563      5947          3140  ...         23     8      8
1         573       608      5900          3114  ...         25    12     12
2         598       775      4534          3309  ...          8    16      9
3         616       861      4398          3469  ...          6    10     11
4         633       920      4631          3700  ...          7    10      5
5         531       887      3680          3373  ...          4     4      5
6         608      1070      3609          3889  ...          0     4      5
7         577       861      3228          3230  ...          3     2      5
8         522       766      2683          2847  ...          1     4      5
9         440       682      2159          2492  ...          0     2      3
10        392       575      2052          2188  ...          5     4      1
11        389       723      2278          2624  ...          0     0      2
12        384       619      1767          2180  ...          0     0      1
13        336       639      1843          2368  ...          1     1      2
14        358       629      1753          2152  ...          1     1      2
15        327       565      1500          1834  ...          0     0      2
16        330       535      1421          1763  ...          0     0      1
17        292       492      1642          1951  ...          0     3      2
18        256       399      1182          1371  ...          0     2      0
19        242       487      1347          1746  ...          1     1      1
20        172       208       892           789  ...          1     1      2
21        175       349       819          1157  ...          0     0      0
22        148       305       760          1088  ...          0     0      0
23        180       295       750          1022  ...          0     0      0
24        112       197       520           633  ...          0     0      0
25        149       295       716          1050  ...          0     0      0
26        128       211       619           744  ...          0     0      0
27        143       298       607           992  ...          0     0      0
28         81       174       458           623  ...          0     0      0
29         95       194       430           632  ...          0     0      0
..        ...       ...       ...           ...  ...        ...   ...    ...
31         95       202       492           720  ...          0     0      1
32        127       217       393           662  ...          0     0      0
33         92       158       291           489  ...          0     0      0
34         79       152       419           588  ...          0     0      1
35         76       118       320           410  ...          0     0      0
36         56       110       244           366  ...          0     0      0
37         63       137       285           430  ...          0     0      0
38         45        63       199           241  ...          0     0      0
39         46        90       202           296  ...          0     0      0
40         50        95       216           310  ...          0     0      0
41         44        83       165           221  ...          0     0      0
42         37        78       155           253  ...          0     0      0
43         27        52       139           167  ...          0     0      0
44         21        66       227           308  ...          0     1      0
45         44        44       101           139  ...          0     0      0
46         16        66       181           295  ...          0     0      0
47         23        37        62           117  ...          0     0      0
48         24        37        70           115  ...          0     0      0
49         16        62       145           252  ...          0     0      0
50         13        48       121           183  ...          0     0      0
51         14        37       153           184  ...          0     0      0
52         18        33        71           116  ...          0     0      0
53          6        30        97           131  ...          0     0      0
54         14        41        70           182  ...          0     0      0
55         11        19        36            55  ...          0     0      0
56         10        20        38            66  ...          0     0      0
57          8        15        37            57  ...          0     0      0
58          5        18        51            85  ...          0     0      0
59          4        21        34            65  ...          0     0      0
60          0         0         0             0  ...          0     0      0

   Fifth Sixth   T Debut  Since/LastApp BestPosition    GD
0      3     4  79  1929           1929            1  2807
1      4     6  83  1929           1929            1  2786
2      7     6  56  1929        2002-03            1  1225
3     10     7  50  1931        1987-88            1   929
4      8    10  49  1929           1929            1   931
5     12     6  32  1934        2001-02            1   307
6      2     5  16  1929        1994-95            3  -280
7      4     3  19  1929        2010-11            1    -2
8      4     4  18  1939        2012-13            2  -164
9      4     4  14  1932        2015-16            1  -333
10     0     1  12  1941        2014-15            1  -136
11     4     5  11  1939        2012-13            4  -346
12     1     1   3  1948        2013-14            4  -413
13     0     1   5  1929        2011-12            2  -525
14     2     1   7  1944        2015-16            2  -399
15     2     2   6  1935        2016-17            4  -334
16     0     1   2  1949        2008-09            4  -342
17     2     4  11  1933        2000-01            3  -309
18     2     1   5  1960        2012-13            3  -189
19     1     1   5  1951        2015-16            2  -399
20     3     2   9  1998        2013-14            2   103
21     0     2   2  1941        2016-17            6  -338
22     0     0   0  1977        2015-16            8  -328
23     1     1   2  1959        2014-15            5  -272
24     0     1   1  2004        2015-16            6  -113
25     1     4   5  1935        2010-11            5  -334
26     2     0   2  1961        2009-10            5  -125
27     0     0   0  1940        2007-08           11  -385
28     0     1   1  1930        2016-17            6  -165
29     0     1   1  1963        2015-16            6  -202
..   ...   ...  ..   ...            ...          ...   ...
31     1     0   2  1943        1987-88            4  -228
32     0     0   0  1977        2005-06           12  -269
33     0     0   0  1987        1996-97            7  -198
34     2     0   3  1941        1990-91            4  -169
35     0     0   0  1991        2004-05            7   -90
36     0     0   0  2007        2014-15            8  -122
37     1     0   1  1962        2014-15            5  -145
38     0     0   0  1994        1997-98           10   -42
39     0     0   0  1978        2008-09            8   -94
40     0     0   0  1971        1979-80           12   -94
41     0     0   0  1963        1969-70            7   -56
42     0     0   0  1999        2008-09           17   -98
43     0     0   0  2014        2014-15           10   -28
44     3     0   4  1929        1934-35            3   -81
45     0     0   0  1990        1992-93            9   -38
46     0     0   0  1947        2006-07            7  -114
47     0     0   0  1996        1998-99           17   -55
48     0     0   0  1995        1997-98           19   -45
49     0     0   0  1945        1950-51           10  -107
50     0     0   0  1953        1957-58           14   -62
51     0     1   1  1929        1931-32            6   -31
52     0     0   0  1979        1980-81           10   -45
53     0     0   0  1929        1930-31            8   -34
54     0     0   0  1950        1993-94           16  -112
55     0     0   0  2016        2016-17           17   -19
56     0     0   0  2009        2009-10           20   -28
57     0     0   0  1956        1956-57           16   -20
58     0     0   0  1951        1951-52           16   -34
59     0     0   0  1955        1955-56           15   -31
60     0     0   0  2017        2017-18            9     0

[61 rows x 21 columns]
Maximum Goal Difference:  Real Madrid
Minimum Goal Difference:  Racing Santander
Top 5 Teams on goal difference basis
0        Real Madrid
1          Barcelona
2    Atletico Madrid
3           Valencia
4    Athletic Bilbao
Name: Team, dtype: object
Sum of points based on 'Best Position
BestPosition
1     27933
2      6904
3      5221
4      6563
5      1884
6      2113
7      1186
8      1134
9        96
10      450
11      445
12      511
14       71
15       14
16       81
17      266
19       81
20       34
Name: Points, dtype: int64